module.exports = {
	"view_users": "View users",
	"create_users": "Create users",
	"delete_users": "Delete users",
	"assign_users": "Assign users to instructors",
	"track_payments": "Track payments",
	"upload_doc": "Upload documents",
	"view_sub": "View submissions",
	"grade_sub": "Grade submissions",
	"fill_forms": "Fill forms",
	"make_payment": "Make payment",
	"de_activate_users": "Activate/deactivate users",
	"reset_passwords": "Reset passwords",
	"reset_password": "Reset my password",
	"edit_role": "Edit role",
	"view_sub": "View submissions",
	"add_notif": "Add notifications",
	'view_profile': 'View profiles',
	'add_class': 'Add class',
	'edit_class': 'Edit class',
	'edit_detail': 'Edit details',
	'message_user': 'Message other users',
	'view_feedback': 'View feedback'
};